name: universidad_lg_24
description: Aplicación desarrollada para el manejo de las integraciones
  previstas de universidad_lg
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1

  carousel_slider: ^4.2.1
  chewie: ^1.8.1
  cool_stepper_reloaded: ^3.2.6
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flick_video_player: ^0.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_countdown_timer: ^4.1.0

  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_widget_from_html: ^0.15.1
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  kalender: ^0.4.1
  rainbow_color: ^2.0.1
  string_extensions: ^0.7.1
  video_player: ^2.9.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/icono-ulg.png"
  remove_alpha_ios: true
  min_sdk_android: 21
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/back-login.jpg
    - assets/images/logo-new.png
    - assets/images/new_logo.png
    - assets/images/biblioteca.png
    - assets/images/club.png
    - assets/images/back-perfil.png
    - assets/images/logo-new2.png
    - assets/images/IMG_3719.PNG
    - assets/images/Grupo 77.png
    - assets/images/Home.png
    - assets/static/
    - assets/images/
    - assets/png/
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
          weight: 400
          style: normal
