name: universidad_lg_24
description: Aplicación desarrollada para el manejo de las integraciones
  previstas de universidad_lg
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7

  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  # fonts:
  #   - family: TitilliumWeb
  #     fonts:
  #       - asset: fonts/Archivo-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Archivo-Regular.ttf
  #         weight: 400
  #         style: normal
