name: universidad_lg_24
description: Aplicación desarrollada para el manejo de las integraciones
  previstas de universidad_lg
version: 2.0.0+7
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  cached_network_image: ^3.4.1

  carousel_slider: ^5.0.0
  chewie: ^1.8.5
  cool_stepper_reloaded: ^3.2.6
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flick_video_player: ^0.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_countdown_timer: ^4.1.0

  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_secure_storage: ^9.2.2
  flutter_widget_from_html: ^0.15.3
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  kalender: ^0.4.2
  pull_to_refresh: ^2.0.0
  rainbow_color: ^2.0.1
  string_extensions: ^0.7.3
  video_player: ^2.9.2
  webview_flutter: ^4.10.0
  youtube_player_iframe: ^5.2.1

dev_dependencies:
  bloc_test: ^9.1.7
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/ic_launcher.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/png/ic_launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/back-login.jpg
    - assets/images/logo-new.png
    - assets/images/new_logo.png
    - assets/images/biblioteca.png
    - assets/images/club.png
    - assets/images/back-perfil.png
    - assets/images/logo-new2.png
    - assets/images/IMG_3719.PNG
    - assets/images/Grupo 77.png
    - assets/images/Home.png
    - assets/static/
    - assets/images/
    - assets/png/
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
          weight: 400
          style: normal
